# Generated by Django 4.1.13 on 2023-12-14 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datos',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('IDSensor', models.CharField(max_length=40)),
                ('nivelContaminacion', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('latitud', models.DecimalField(decimal_places=6, default=0.0, max_digits=10)),
                ('longitud', models.DecimalField(decimal_places=6, default=0.0, max_digits=10)),
                ('fechaRegistro', models.CharField(max_length=20)),
                ('horaPub', models.CharField(max_length=20)),
                ('minutoPub', models.CharField(max_length=20)),
                ('segundoPub', models.CharField(max_length=20)),
            ],
        ),
    ]
